name: "Pull Request Analytics"
author: "Aleksei Simatov"
description: "Github action to create detailed PRs report"
branding:
  icon: "trending-up"
  color: "orange"
inputs:
  GITHUB_TOKEN:
    description: "Github token"
    required: true
  GITHUB_OWNERS_REPOS:
    description: "Github owner/repository list separated by comma"
    required: true
  GITHUB_REPO_FOR_ISSUE:
    description: "Github repo for issue"
    required: true
  GITHUB_OWNER_FOR_ISSUE:
    description: "Github owner for issue"
    required: true
  AMOUNT:
    description: "Amount of PRs"
    required: false
    default: "100"
  REPORT_DATE_START:
    description: "Start date for report(yyyy/MM/d)"
    required: false
  REPORT_DATE_END:
    description: "End date for report(yyyy/MM/d)"
    required: false
  CORE_HOURS_START:
    description: "Start time of core hours(HH:mm)"
    required: false
  CORE_HOURS_END:
    description: "End time of core hours(HH:mm)"
    required: false
  PERCENTILE:
    description: "Percentile value for timeline"
    required: false
    default: "75"
  LABELS:
    description: "Multiple labels for issue separated by comma"
    required: false
  ASSIGNEES:
    description: "Multiple assignees for issue separated by comma"
    required: false
  ISSUE_TITLE:
    description: "Title for issue"
    required: false
  ASSIGNEE:
    description: "assignee for issue"
    required: false
  AGGREGATE_VALUE_METHODS:
    description: "Aggregate value methods separated by comma. Can take values: 'percentile', 'average', 'median'"
    required: false
    default: "percentile"
  HIDE_USERS:
    description: "Hidden users separated by comma"
    required: false
  SHOW_USERS:
    descriptions: "Shown users separated by comma"
    required: false
  INCLUDE_LABELS:
    description: "Includes only PRs with mentioned labels. Values should be separated by comma"
    required: false
  EXCLUDE_LABELS:
    description: "Excludes PRs with mentioned labels. Values should be separated by comma"
    required: false
  TIMEZONE:
    description: "Timezone to use in action"
    required: false
outputs:
  JSON_COLLECTION:
    description: "Output file"
runs:
  using: "node20"
  main: "build/index.js"
